@startuml commmands_class

interface Command {
    + CommandResponse execute()
    + Class[] getArgumentsTypes()
    + boolean isVaildArguments()
}

abstract class AbstractCommand implements Command

abstract class CollectionCommand extends AbstractCommand {

}

class Help extends AbstractCommand

class User

hide AbstractCommand empty members
hide CollectionCommand empty members
hide class empty members
hide interface empty members

@enduml